"""Added note field

Revision ID: 402972acddd0
Revises: 48f465bb664d
Create Date: 2023-01-15 02:08:42.876586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402972acddd0'
down_revision = '48f465bb664d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
